### ISSUE TITLE
The compilation of RVV test program failed

### ISSUE THREAD

**Issue by pavitrar20** [compiler-dev/llvm-rv#14]
I followed all the steps listed in this page. 
Yet I got compilation errors

in directory LLVM-RV/RVV-TEST
Command:
clang vadd_vv_i32.c -O2 --target=riscv32 -march=rv32imafcv --sysroot=$TOOL_CHAIN_PATH/riscv-unknown-elf --gcc-toolchain=$TOOL_CHAIN_PATH -o vadd_vv_i32.out

In file included from vadd_vv_i32.c:2:
In file included from /home/ubuntu/Spike/riscv32-unknown-elf/include/stdio.h:29:
/home/ubuntu/Spike/riscv32-unknown-elf/include/_ansi.h:10:10: error: 'newlib.h' file not found with <angled> include; use "quotes" instead
#include <newlib.h>
         ^~~~~~~~~~
         "newlib.h"
In file included from vadd_vv_i32.c:2:
In file included from /home/ubuntu/Spike/riscv32-unknown-elf/include/stdio.h:29:
In file included from /home/ubuntu/Spike/riscv32-unknown-elf/include/_ansi.h:10:
/home/ubuntu/Spike/riscv32-unknown-elf/include/newlib.h:14:10: error: '_newlib_version.h' file not found with <angled> include; use "quotes" instead
#include <_newlib_version.h>
         ^~~~~~~~~~~~~~~~~~~
         "_newlib_version.h"
In file included from vadd_vv_i32.c:2:
In file included from /home/ubuntu/Spike/riscv32-unknown-elf/include/stdio.h:29:
/home/ubuntu/Spike/riscv32-unknown-elf/include/_ansi.h:11:10: error: 'sys/config.h' file not found with <angled> include; use "quotes" instead
#include <sys/config.h>
         ^~~~~~~~~~~~~~
         "sys/config.h"
In file included from vadd_vv_i32.c:2:
In file included from /home/ubuntu/Spike/riscv32-unknown-elf/include/stdio.h:29:
In file included from /home/ubuntu/Spike/riscv32-unknown-elf/include/_ansi.h:11:
/home/ubuntu/Spike/riscv32-unknown-elf/include/sys/config.h:4:10: fatal error: 'machine/ieeefp.h' file not found
#include <machine/ieeefp.h>  /* floating point macros */
         ^~~~~~~~~~~~~~~~~~
4 errors generated.

Many other errors in running SPike as well (even if the path for stdio.h which was not in the default path was specified explcitly)-
A simple hello program - 

spike pk hello
error: bad --varch option 'vlen:128,elen:32,slen:128'. Unsupported token

**Comment by dingchuanxin** [comment]
Sorry to reply so late.  You can send me email (chuanxin.ding@compiler-dev.com) if you have other questions.
First we cannot reproduce the header files (newlib.h) missing issue. Please check if your environment is configured correctly. Could you find the newlib.h in the sub-directory of $TOOL_CHAIN_PATH after building riscv-gnu-toolchain?

The spike error is caused by the version of riscv-isa-sim. The newest  spike cannot receive the option vlen:128,elen:32,slen:128. You can resolve this problem by checkout '8977224a' commit id of spike. Such as: `git checkout 8977224a` in the riscv-isa-sim repository directory before building spike.
